# Site settings
title: "HENAT Lab"
description: "Research in Network Analysis and Technology"
baseurl: ""  # Leave blank for GitHub Pages
url: "https://ucf-henat.github.io"  # Your website URL

# Author information
author:
  name: "Your Name"
  email: "your-email@domain.com"
  affiliations:
    - "Department of XYZ, University of ABC"
    - "Another Affiliation or Research Group"

# Social media links (optional)
social:
  google_scholar: "https://scholar.google.com/citations?user=your_id"
  researchgate: "https://www.researchgate.net/profile/Your_Name"
  twitter: "https://twitter.com/your_twitter_handle"
  linkedin: "https://www.linkedin.com/in/your_profile"

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Theme settings
theme: minima  # Change if using another theme

# Exclude files from Jekyll processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
